"""Pack local PCM recordings into short audio sprites; no codec dependencies."""
import hashlib
import json
from pathlib import Path
import wave
from array import array

ROOT = Path(__file__).resolve().parents[1]
texts = json.loads((ROOT / '_local/speech/catalog.json').read_text(encoding='utf-8'))
out = ROOT / 'audio/speech'
out.mkdir(parents=True, exist_ok=True)
rate = 16000
buffers, frames, clips, assets = [], 0, {}, []


def flush():
    global buffers, frames
    if not buffers:
        return
    pcm = b''.join(buffers)
    name = f'pack-{len(assets):03d}-{hashlib.sha256(pcm).hexdigest()[:10]}.wav'
    with wave.open(str(out / name), 'wb') as target:
        target.setnchannels(1)
        target.setsampwidth(2)
        target.setframerate(rate)
        target.writeframes(pcm)
    assets.append('./audio/speech/' + name)
    buffers, frames = [], 0


for text in texts:
    digest = hashlib.sha256(text.encode()).hexdigest()
    with wave.open(str(ROOT / f'_local/speech/wav/{digest}.wav'), 'rb') as source:
        assert (source.getnchannels(), source.getsampwidth(), source.getframerate()) == (1, 2, rate)
        count = source.getnframes()
        audio = source.readframes(count)
    samples = array('h', audio)
    audible = [i for i, sample in enumerate(samples) if abs(sample) > 80]
    if not audible:
        raise ValueError(f'Silent recording: {text!r}')
    start = max(0, audible[0] - rate // 40)
    end = min(len(samples), audible[-1] + rate // 25)
    audio = samples[start:end].tobytes()
    count = end - start
    if frames + count > rate * 45:
        flush()
    clips[text] = [len(assets), frames / rate, count / rate]
    buffers.append(audio)
    frames += count
flush()
manifest = {'version': 1, 'voice': 'Microsoft Heami Desktop', 'assets': assets, 'clips': clips}
(ROOT / 'js/data/speech-manifest.js').write_text(
    '// Generated by scripts/pack-speech.py; shared by the app and service worker.\n'
    + 'self.OFFLINE_SPEECH = ' + json.dumps(manifest, ensure_ascii=False, separators=(',', ':')) + ';\n', encoding='utf-8')
print(f'Packed {len(clips)} phrases into {len(assets)} files ({sum(p.stat().st_size for p in out.glob("*.wav"))/1024/1024:.1f} MiB).')
